### ISSUE TITLE
Automated Analysis showing up blank (for Rust)

### ISSUE THREAD

**Issue by anall** [exercism/rust-analyzer#36]
This is on a mentoring request, but I have also seen this when I am doing exercises myself.

![image](https://user-images.githubusercontent.com/12371/141380185-ff9209c7-fbc9-4ee4-b1c1-9ad10c13e471.png)

The specific mentoring request is for `gigasecond`, and the code from the [mentoring request](https://exercism.org/mentoring/requests/8b1b225266764000ba882dbcd86b825c) is:

```
use time::PrimitiveDateTime as DateTime;
use time::Duration as Duration;

// Returns a DateTime one billion seconds after start.
pub fn after(start: DateTime) -> DateTime {
    start + Duration::seconds(1000000000)
}
```

Running this crate locally on that code gives:

```
{
  "status": "refer_to_mentor",
  "comments": [
    "The solution could not be parsed."
  ]
}
```

But I do not know if that is what the live site is giving.

**Comment by anall** [comment]
Correction, I had the file in the wrong place and also had a stray garbage byte at the end of the file -- the actual `analysis.json` is:

```
{
  "status": "refer_to_mentor",
  "comments": [
    "I like this solution directly adds `Duration` to `start` with the `+` operator.",
    "Did you know that rust number literals can have `_` in them to make them more readable? For example: `1_000`"
  ]
}
```

**Comment by ErikSchierboom** [comment]
I'm almost sure this is because the output format is the old analysis format. See https://github.com/exercism/docs/blob/main/building/tooling/analyzers/interface.md#output-format for a description of the new format. The comments should be keys into the https://github.com/exercism/website-copy/tree/main/analyzer-comments/rust directory.

**Comment by iHiD** [comment]
> I'm almost sure this is because the output format is the old analysis format

FYI, I don't believe there's ever been a format where messages haven't gone via website-copy.

**Comment by ErikSchierboom** [comment]
No that's true. I should have rephrased that :)

**Comment by ErikSchierboom** [comment]
@anall I've just pushed a fix for this. Could you try re-running the tests to see if the analysis now shows up properly?

**Comment by anall** [comment]
Looks great now. Thanks.
